#!/usr/bin/env bash

required_metadata_values=(
  EASYTIER_APP_VERSION
  EASYTIER_BUILD_CHANNEL
  EASYTIER_BUILD_NUMBER
  EASYTIER_BUILD_TIME
  EASYTIER_GUI_COMMIT
  EASYTIER_GATEWAY_VERSION
  EASYTIER_CORE_TAG
  EASYTIER_CORE_COMMIT
)
for metadata_variable in "${required_metadata_values[@]}"; do
  [[ -n "${!metadata_variable:-}" ]] || {
    printf 'Missing Xcode metadata value: %s\n' "$metadata_variable" >&2
    return 1
  }
done

EASYTIER_XCODE_METADATA_ARGS=(
  "MARKETING_VERSION=$EASYTIER_APP_VERSION"
  "CURRENT_PROJECT_VERSION=$EASYTIER_BUILD_NUMBER"
  "EASYTIER_BUILD_TIME=$EASYTIER_BUILD_TIME"
  "EASYTIER_BUILD_CHANNEL=$EASYTIER_BUILD_CHANNEL"
  "EASYTIER_GUI_COMMIT=$EASYTIER_GUI_COMMIT"
  "GATEWAY_BUILD_TIME=$EASYTIER_BUILD_TIME"
  "GATEWAY_COMMIT=$EASYTIER_GUI_COMMIT"
  "GATEWAY_VERSION=$EASYTIER_GATEWAY_VERSION"
  "EASYTIER_CORE_TAG=$EASYTIER_CORE_TAG"
  "EASYTIER_CORE_COMMIT=$EASYTIER_CORE_COMMIT"
)
